database:
  mongo:
    url: mongodb+srv://dark-souls:1qaz%40WSX@cluster0.53eb6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    name: chatbot-go
    username: ""
    password: ""
    host: localhost
    port: 27017
    ssl_mode: disable
    ssl_root_cert: ""
    cluster: ""
